### ISSUE TITLE
Praise

### ISSUE THREAD

**Issue by mightyiam** [staltz/fantasy-observable#3]
Well, for one, this was easy for me to understand. I've found it well-written. On the TC39 proposal I've spent far too much time now, trying to understand.

I'm happy that I do not see the keyword `new` anywhere.

This should catch on just like we see widespread use of promises, where multiple values are expected.

**Comment by SteveALee** [comment]
I agree - let's pass it around. I've already tweeted.

**Comment by staltz** [comment]
Thanks :)
