### ISSUE TITLE
I'm not getting description of Subject

### ISSUE THREAD

**Issue by mightyiam** [staltz/fantasy-observable#4]
Current text of Subject:

> A Subject is both an Observable and Observer. It is both a Producer and a Consumer. You may use its Observer methods to send data to the Subject, while you may use the Observable subscribe method to consume data from the Subject.

The sentence I'm having trouble with is

> You may use its Observer methods to send data to the Subject,

I lost you, here. I lost you at the word "Subject". The way I read this sentence, "it", is the Subject. So it reads like this:

> You may use the Subject's Observer methods to send data to the Subject,

This doesn't look right to me, though.

**Comment by staltz** [comment]
> > You may use the Subject's Observer methods to send data to the Subject

> This doesn't look right to me, though.

Yep, that's correct. What's the problem?

**Comment by mightyiam** [comment]
So, "You may use the Subject's Observer methods to send data to itself"?

What's the point of it sending data to itself? Perhaps if I knew what a Subject is good for.

**Comment by SteveALee** [comment]
@mightyiam No, not to itself. It forwards. For example they can interface from imperative to streams. you call next and a subject emits an item on its stream. See this [examples in RxJS docs](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/subject.md).

**Comment by staltz** [comment]
Yeah I think Steve answered it. Also this explains it: http://reactivex.io/rxjs/manual/overview.html#subject

**Comment by SteveALee** [comment]
Shame Rx confuses things by introducing it's singlecast (single function call) / multicast (call all observers) issue with it's subjects :(

**Comment by mightyiam** [comment]
So, is this correct?

```js
const subject = getSubjectSomehow()

subject.subscribe({
  next: x => console.log(x),
  error: e => console.log(e),
  complete: () => console.log('complete')
)}

subject.next('foo') // foo
subject.complete() // complete
```

**Comment by staltz** [comment]
Yes

**Comment by mightyiam** [comment]
How about this version:

> A Subject is both an Observable and an Observer—both a Producer and a Consumer. You may use its Observer methods (`next`, `error` and `complete`) to send it data, while you may also use its Observable `subscribe` method to consume its data.

**Comment by staltz** [comment]
yeah

**Comment by mightyiam** [comment]
PR @ #5.
